services:
  ollama:
    image: docker.io/ollama/ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    devices:
      - nvidia.com/gpu=all   # Podman CDI 経由の GPU パススルー

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    restart: unless-stopped
    depends_on:
      - ollama
    volumes:
      - open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'

  caddy:
    image: caddy:alpine
    container_name: caddy_openwebui
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - caddy_certs:/certs
      - caddy_config:/config
      - caddy_data:/data
      - caddy_sites:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  ollama: {}
  open-webui: {}
  caddy_certs: {}
  caddy_config: {}
  caddy_data: {}
  caddy_sites: {}
